export const restaurantList = [
  {
    index: 1,
    checkProject: '食品经营许可证合法有效、与经营场所（实体门店）地址一致。',
    maybeRisk: '无证违法经营。',
    reasonAnalysis: '对食品安全法及相关规定不熟悉，经营上会有风险。',
    measures: '增强法律意识，依法经营。',
    isImportant: true,
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 2,
    checkProject: '未超出许可经营项目开展餐饮服务活动。',
    maybeRisk: '超出许可范围经营。',
    reasonAnalysis: '对食品安全法及相关规定不熟悉，经营上会有风险。',
    measures: '增强法律意识，依法经营。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 3,
    checkProject: '在经营场所的显著位置悬挂或者摆放食品经营许可证正本，或以电子形式公示。',
    maybeRisk: '降低消费者对门店认可对，不利于监管部门检查，容易引起投诉。',
    reasonAnalysis: '对相关法律法规掌握不熟。',
    measures: '按要求悬挂或摆放。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 4,
    checkProject:
      '曾开展过日常监督检查的餐饮服务提供者，应当按规定在经营场所醒目位置张贴或者公开展示对消费者有重要影响的监督检查结果记录表。',
    maybeRisk: '对存在问题未进行改进，食品安全隐患未消除。',
    reasonAnalysis: '担心公示问题后对门店产生负面影响',
    measures: '  按制度落实。	提高内部监督力度，由员工和消费者进行督促改进。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 5,
    checkProject: '应当公示从事接触直接入口食品工作的从业人员的有效健康证明。',
    maybeRisk: '不知道从业者是否患有不得从事直接入口食品工作的情况。',
    reasonAnalysis: '人手不够，临时招聘。',
    measures: '没有食品安全风险意识，上岗人员必须有有效健康证。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 6,
    checkProject:
      '入网餐饮服务提供者应当在线上经营活动主页面公示餐饮服务提供者名称、地址、食品经营许可证等信息，公示信息真实，及时更新。',
    maybeRisk: '容易出现无证或许可证过期单位上网。违反食品安全法；当出现食品安全问题时难以协调和赔付。',
    reasonAnalysis:
      '自己没有经营地点，或者经营地点条件差，不能获得许可证。网络单位只以经济利益为目标，疏于管理，让无证单位上网。',
    measures: '入网单位要有法律意识，按照要求公示信息真实性，并及时更换。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 7,
    checkProject:
      '有每日健康检查（晨检）记录。从事接触直接入口食品工作的从业人员持有有效的健康证明，未患有碍食品安全病症或手部有伤口。',
    maybeRisk: '持证上岗人员临时出现腹痛、腹泻、手部伤口等疾病，而产生的风险隐患。',
    reasonAnalysis: '制度不落实，人手不够。',
    measures: '严格落实人员晨检制度。',
    isImportant: true,
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 8,
    checkProject: '在岗从业人员保持良好个人卫生，手部清洁，无留长指甲、涂指甲油、饰物外露等情形。',
    maybeRisk: '个人卫生差（包括留长指甲、涂指甲油，饰物外露）。',
    reasonAnalysis: '容易污染食品，产生风险隐患。',
    measures: '严格落实人员晨检制度。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 9,
    checkProject: '在岗从业人员穿戴洁净的工作衣帽。专间、专用操作区和其他操作区的从业人员工作服有明显区分。',
    maybeRisk: '不清洁的工作服污染食品，未认识餐饮分区管理要求。',
    reasonAnalysis: '员工省事心里作怪。',
    measures: '落实制度管理。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 10,
    checkProject: '专间及专用操作区内的从业人员操作时，佩戴清洁的口罩，口罩遮住口鼻。',
    maybeRisk: '专间是食品安全风险最高的区域，人员未按操作要求工作。',
    reasonAnalysis: '容易污染食品，未认识餐饮分区管理要求，员工省事心里作怪。',
    measures: '落实制度管理。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 11,
    checkProject: '随机抽查的餐饮服务提供者的食品、食品添加剂、食品相关产品有进货查验记录和合格证明文件。',
    maybeRisk: '容易购进不符合食品安全标准的食品。',
    reasonAnalysis: '制度未落实，进货量少、进货途径不正规，贪图便宜。',
    measures: '落实索票索证管理制度要求。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 12,
    checkProject:
      '食品贮存区不存在食品与非食品混放情形，未存放有毒有害物质；食品贮存符合分类、分架、离墙、离地、有标识等要求。',
    maybeRisk: '容易出现污染食品的情况。',
    reasonAnalysis: '未将食品分类、分架、离地、离墙存放，且库房不通风，容易出现食品原料霉变，容易隐藏有害昆虫。',
    measures: '落实食品原料库房管理要求。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 13,
    checkProject:
      '需冷冻（藏）的食品原料、半成品和成品及时按要求进行冷冻（藏）。冷冻（藏）设施中的食品不存在原料、半成品、成品混放等情形；冷冻（藏）设施设有可正确显示内部温度的测温装置，冷冻（藏）温度符合要求。',
    maybeRisk: '因储存不当，温度控制不好，容易使食品腐败变质。',
    reasonAnalysis: '制度未落实，未按照要求储存食品；冷冻冷藏设备无温度显示设备或已损坏，不能按要求储存食品。',
    measures: '加强制度落实；增设温度显示设备；加强设备保养维修。',
    isImportant: true,
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 14,
    checkProject: '现场应当（发现）无标签标识、无法说明来源以及其他明令禁止生产经营的物质。',
    maybeRisk: '可能购进的是不合格的食品原料，或者含有有毒有害成分的原料。',
    reasonAnalysis: '未按规定购进食品原料，或者贪图价格便宜购进违规食品原料',
    measures: '严格落实食品安全法相关规定，不购进无标识预包装食品和明令禁止生产经营的物质。',
    isImportant: true,
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 15,
    checkProject:
      '在加工间和贮存设施内随机抽查的食品原料感官性状无异常、食品包装和标签标识符合要求。未采购、贮存、使用散装食盐。',
    maybeRisk:
      '食品原料感官异常说明有腐败变质的可能；食品包装的问题，反映出企业在生产、储存、运输中的问题；食品标签问题反映为生产不规范。购买散装盐容易出现购买工业盐的可能。上述均存在食品安全风险。',
    reasonAnalysis: '1、未落实食品原料在采购相关要求；2、未落实食品原料在存放相关要求。',
    measures: '落实食品原料储存、加工操作制度，增添设备，完善流程。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 16,
    checkProject:
      '对变质、超过保质期或者回收的食品进行显著标示或者单独存放在有明确标志的场所，应当及时进行无害化处理、销毁等，并如实记录。',
    maybeRisk: '存在误用过期食品和不合格食品的可能。',
    reasonAnalysis: '未按制度要求，严格落实单独存放和及时销毁的规定。',
    measures: '严格落实变质、过期或者回收食品存放和无害化处理等规定。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 17,
    checkProject:
      '食品加工用水水质符合生活饮用水卫生标准。加工制作现榨果蔬汁和食用冰等直接入口食品的用水通过净水设施处理，或使用预包装饮用水、煮沸冷却后的生活饮用水。',
    maybeRisk:
      '因水污染或者使用不符合生活饮用水卫生标准的食品用水，容易发生食品安全事故。自制饮品不再加热，目前使用的自来水不能保证自制饮品食品安全要求。',
    reasonAnalysis: '食品安全意识不强，想节省费用，未按食品安全相关要求，增添设备。',
    measures: '落实制度，增添设备，完善流程。',
    isImportant: true,
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 18,
    checkProject: '具有与其加工制作的食品品种、数量相适应的加工场所及设施设备等。',
    maybeRisk: '超量、超范围加工制作食品，存在储存条件问题导致食品原料腐败变质和加工制作交叉污染等食品安全风险。',
    reasonAnalysis: '过度考虑经济利益，增加食品安全风险。',
    measures: '严格按照许可项目和接待能力加工制作食品。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 19,
    checkProject:
      '原料、半成品、成品及其盛放容器和加工制作工具区分标识明显、分开放置和使用；防止食品交叉污染的措施有效。',
    maybeRisk:
      '原料、半成品、成品因加工过程不同，其所含有害物质（特别是微生物）含量不同，如果混用、混放，极易出现食品安全事故。',
    reasonAnalysis: '没有食品安全风险意识，工用具储备不够，操作间较小，未分区。',
    measures: '严格操作规范，明确操作间分区操作，避免出现交叉污染。',
    isImportant: true,
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 20,
    checkProject:
      '食品原料洗净后使用。各类水池应当有明显标识标明用途，分类清洗动物性食品、植物性食品和水产品。未经清洁的禽蛋使用前清洁外壳。',
    maybeRisk:
      '1、未清洗的食品原料，自身容易带有杂质和污染物；2、各类食品原料带有细菌不同，容易交叉污染；3、禽蛋带有沙门氏菌，容易引起食物中毒。',
    reasonAnalysis: '食品安全风险意识不强，工用具储备不够，未分类区分使用和储存。',
    measures: '严格操作规范，明确使用区域用途，避免出现交叉污染。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 21,
    checkProject:
      '盛放调味料的容器保持清洁，加盖存放。煎炸油的色泽、气味、状态无异常，必要时进行检测。油炸类食品、烧烤类食品、火锅类食品、糕点类食品、自制饮品等加工过程符合要求。',
    maybeRisk:
      '1、调味品容器未加盖，容易被其他污染物和有害生物污染；2、容易出现油脂酸败等危害身体健康的物质；3、容易出现使用不合格食品原料和出现交叉污染。',
    reasonAnalysis:
      '1、未按规范操作，操作者未养成习惯；2、管理未跟上，过度节省开支；3、制度未落实，无内部自查机制或有而未落实。',
    measures: '建立制度并实施，开展自查机制，落实主体责任要求。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 22,
    checkProject: '专间及专用操作区的标识、设施、人员及操作应当符合要求。',
    maybeRisk: '该区域是不再加热的熟食品加工区，如果无明确标识及规范人员行为，极易因交叉污染发生食品安全事故。',
    reasonAnalysis: '对生熟食品交叉污染危害性认识不足，对操作规范不熟悉。',
    measures: '严格按照食品安全操作规范，加强员工培训。',
    isImportant: true,
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 23,
    checkProject:
      '学校（含托幼机构）食堂、养老机构食堂、医疗机构食堂、建筑工地食堂等集中用餐单位的食堂以及中央厨房、集体用餐配送单位、一次性集体聚餐人数超过100人或为重大活动供餐的餐饮服务提供者，应当按规定留样。',
    maybeRisk:
      '发生安全事故后，未能提供留样食品，会拖延事故调查过程的进度，对后期处置工作极为不利，也不能更好沥青事件是否与食品有关。',
    reasonAnalysis: '没有食品留样意识，未落实承担该工作人员与制度要求，也无留样设备与工具。',
    measures: '严格按照食品留样要求，加强专业培训。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 24,
    checkProject:
      '中小学、幼儿园食堂未制售冷荤类食品、生食类食品、裱花蛋糕，未加工制作四季豆、鲜黄花菜、野生蘑菇、发芽土豆等高风险食品，未设置酒销售点。',
    maybeRisk:
      '1、冷荤类食品、生食类食品、裱花蛋糕等此类食品均是在专间制作，因操作不当容易引起食品安全事故；2、四季豆、鲜黄花菜、野生蘑菇、发芽土豆等食品原料含有生物毒素，因处置不当，极易引起食物中毒的高风险食品；3、未成年人无完全行为能力，私自饮酒容易出现社会问题。',
    reasonAnalysis:
      '1、没有风险意识，过度追求经济利益，忽视食品安全风险。2、售酒行为是未认真学习《未成年人保护法》，不了解相关要求。',
    measures:
      '1、中小学、幼儿园食堂严禁制售冷荤类食品、生食类食品、裱花蛋糕，不得加工制作四季豆、鲜黄花菜、野生蘑菇、发芽土豆等高风险食品。2、认真学习《未成年保护法》，并落实相关要求，不设置酒销售点。',
    isImportant: true,
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 25,
    checkProject: '食品添加剂存放、使用、管理符合要求。',
    maybeRisk: '不按规定存放、使用、管理食品添加剂，容易出现食品安全事故和舆情事件。',
    reasonAnalysis: '对国家食品添加剂相关要求不清楚，按照过去习惯盲目使用。',
    measures:
      '严格按照《食品添加剂使用标准》（GB2760-2014）、和《餐饮服务通用卫生规范》（GB31654-2021）存放、使用、管理食品添加剂。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 26,
    checkProject: '未采购、贮存、使用亚硝酸盐等国家禁止在餐饮业使用的品种。',
    maybeRisk: '餐饮服务环节中违规使用亚硝酸盐，容易发生食品安全事故。',
    reasonAnalysis: '不清楚国家规定，师傅带徒弟时，按违法的“老规矩”教徒弟。',
    measures: '按国家公告要求，严禁在餐饮服务环节使用亚硝酸盐。',
    isImportant: true,
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 27,
    checkProject:
      '备餐场所、备餐人员个人卫生、盛装食品成品的容器和分派菜肴整理造型的工具、菜肴围边和盘花符合要求。食品存放温度和时间符合要求。',
    maybeRisk:
      '1、备餐场所是分发熟食品的地方，因卫生差，容易污染食品；2、备餐人员个人卫生问题容易污染食品；3、备餐间容器、工具和菜肴围边和盘花未清洗消毒容易污染熟食品；4、未按温度和时间存放熟食品容易滋生细菌，带来食品安全风险。',
    reasonAnalysis:
      '不了解备餐间的重要性，忽视场地和人员要求，对备餐间容器、工具和菜肴围边和盘花没有清洗、消毒意识，易污染熟食品；对熟食品存放条件（温度、时间）不清楚，未按规范操作。',
    measures: '提高风险意识，制定相关制度、逐一落实，并开展自查机制，将任务落实到人。',
    isImportant: true,
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 28,
    checkProject:
      '采取有效措施，防止供餐过程中食品受到污染。学校食堂就餐区或者就餐区附近应当设置供用餐者清洗手部以及餐具、饮具的用水设施。',
    maybeRisk: '因就餐区没有设置供用餐者清洗手部以及餐具、饮具的用水设施，使手以及未清洗的餐具、饮具污染食品。',
    reasonAnalysis: '老旧餐厅在当初设计时未设置供用餐者清洗手部以及餐具、饮具的用水设施。后期在改建中也未考虑进去。',
    measures: '在以后改建或新设计的食堂中增加此设施。在条件许可的情况下，可在食堂附近区域新增此设施。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 29,
    checkProject:
      '应当具备符合贮存、运输要求的设施设备。食品的传送电梯、配送车辆、存放食品的车厢或配送箱（包）、与食品直接接触的配送容器符合要求。食品配送过程符合要求。',
    maybeRisk:
      '因贮存、运输食品的设施设备不达标，容易污染熟食品。食品的传送电梯、配送车辆、存放食品的车厢或配送箱（包）、与食品直接接触的配送容器不符合要求，有食品安全隐患，食品配送过程不符合要求，容易污染熟食品。',
    reasonAnalysis: '设备、设施不达标，用具工具混用，产生交叉污染的风险。',
    measures: '使用符合要求的设施设备，过程中防止交叉污染和自身腐败变质。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 30,
    checkProject: '中央厨房配送过程中，食品的包装或盛放应当符合要求，包装或盛放容器上标注的信息符合要求。',
    maybeRisk:
      '中央厨房配送过程中，未按要求配送有食品安全风险；包装或盛放容器上未标注相关信息，容易让使用者不清楚是否过期，有无食品安全风险。',
    reasonAnalysis: '中央厨房配送公司未按《餐饮服务食品安全操作规范》要求落实相关标注内容。',
    measures: '中央厨房配送公司应按照《餐饮服务食品安全操作规范》要求，标注相关内容。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 31,
    checkProject: '集体用餐配送单位配送过程中，食品的盛放容器密闭，食品容器上标注的信息符合要求。',
    maybeRisk: '容易让消费者食用过期食品，或不按要求存放和使用食品。',
    reasonAnalysis: '集体用餐配送单位食品安全意识不强，过度节约用人、材料成本。',
    measures: '按照要求在食品容器上标注符合要求的信息。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 32,
    checkProject:
      '外卖送餐人员保持个人卫生、配送箱（包）保持清洁。配送箱（包）中，直接入口食品和非直接入口食品、需低温保存的食品和热食品分隔放置，并保证食品温度符合食品安全要求。',
    maybeRisk:
      '外卖送餐人员配送箱和个人卫生差，让消费者对食品本身也会有疑问。配送箱（包）中，熟食品和其他食品、需低温保存的食品和热食品未分隔放置，未按要求把控温度，容易增加食品腐败变质速度和交叉污染的可能。',
    reasonAnalysis: '外卖送餐人员未注重配送箱和个人卫生，在外卖过程中只看重“多拉快跑”，忽视外卖送餐中的食品安全。',
    measures: '外卖送餐应保持配送箱和个人卫生，各类食品分隔放置，并符合食品温度要求。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 33,
    checkProject: '未在餐饮经营场所内饲养、暂养和宰杀畜禽；场所及设施设备布局合理。',
    maybeRisk:
      '1、活的畜禽带有各种病菌，在餐饮经营场所内饲养、暂养和宰杀，容易污染经营场所；2、场所及设施设备未按要求合理布局，容易出现交叉污染的情况。',
    reasonAnalysis: '在开业时布局就存在问题，或者因后期经营私自改变布局要求。',
    measures: '恢复到前期许可要求的布局，或者对目前布局进行调整，以消除食品安全隐患。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 34,
    checkProject:
      '保持餐饮经营场所环境清洁，墙壁、天花板、门窗、地面、排水沟、操作台、食品加工用具等无破损、霉斑、积油、积水、污垢等。',
    maybeRisk:
      '因使用时间或管理问题出现墙壁、天花板、门窗、地面、排水沟、操作台、食品加工用具等破损、霉斑、积油、积水、污垢等食品安全的环境风险。',
    reasonAnalysis: '单位管理没有落实，操作人员无责任心，日常自查流于形式。',
    measures: '建立制度，落实到位，加强自查。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 35,
    checkProject:
      '冷冻（藏）、保温、陈列、采光、通风、洗手、消毒、三防等设施设备能正常使用。特定餐饮服务提供者具有设施设备维护记录。',
    maybeRisk: '因各设施设备未能正常使用，可能使有害物质大量滋生，为食品安全带来风险。',
    reasonAnalysis: '制度流于形式，责任未真正落实，自查也未到位。',
    measures: '建立制度，落实到位，加强自查。',
    isImportant: true,
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 36,
    checkProject:
      '有害生物防治措施有效，不存在明显的有害生物活动迹象。餐饮服务企业、中央厨房、集体用餐配送单位、学校（含托幼机构）食堂、养老机构食堂、医疗机构等食堂有定期除虫灭害记录。',
    maybeRisk:
      '1、因防治措施不到位，为老鼠、苍蝇、蟑螂等有害生物提供了滋生活动场所，他们自身带有各种病菌，在餐饮服务环节活动，极易污染食品及相关工用具，带来食品安全风险。2、特殊餐饮服务行业的服务对象量大、面广，其中有不少是身体有问题的特殊人群，而自己存放的各种食品原料量会特别大，存在的风险将更大。',
    reasonAnalysis:
      '1、先期硬件不到位，后期人为防治措施又没有跟上，出现食品安全隐患。2、特殊餐饮服务行业只注重产量，忽视有害生物污染的风险。',
    measures:
      '建立制度，落实到位，做好定期除虫灭害记录，并加强自查。如果自身除虫灭害能力不足，可聘请有条件的专业公司上门服务。',
    isImportant: true,
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 37,
    checkProject: '卫生间设置位置符合要求，能够保持清洁。',
    maybeRisk:
      '1、在操作间内设置卫生间容易污染食品；2、卫生间出口对食品处理区，排风装置排向操作间容易把污浊空气排进操作间，增加不安全因素；3、卫生间附近无洗手设施，消费者不能在饭前洗手。',
    reasonAnalysis: '前期设计不足，或者场地较小，设备安装有问题。',
    measures: '在操作间内设置卫生间必须改造；相关设施不足尽量弥补。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 38,
    checkProject: '餐厨废弃物的存放及处置符合要求。',
    maybeRisk: '餐厨垃圾桶未加盖，放置位置容易污染食品处，出现交叉污染的风险。',
    reasonAnalysis: '操作人员意识不强，餐厨垃圾桶盖随便放置。',
    measures: '落实责任制，确定餐厨垃圾桶位置，一定加盖。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 39,
    checkProject: '餐用具清洗水池专用，标有明显标识，满足清洗需要。使用的洗涤剂符合食品安全国家标准，包装标识齐全。',
    maybeRisk:
      '1、餐用具清洗水池未有明显专用标识：一洗、二清、三消毒、四冲洗（化学消毒），容易使操作人员进行其他食品加工使用，容易污染餐饮具，有食品安全风险。2、使用不符合食品安全国家标准的洗涤剂和包装标识不齐全产品，有食品安全风险。',
    reasonAnalysis: '制度未建立，标牌硬件未设置，或责任未落实，人员责任性不强，无制度约束。',
    measures: '落实责任制，硬件标识要设置，加强自查。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 40,
    checkProject:
      '采用物理消毒的，消毒设施（包括一体化洗碗消毒机）运转正常并能满足消毒需要。采用化学消毒的，使用的消毒剂为正规产品，消毒液使用、配制等符合要求。',
    maybeRisk:
      '1、采用物理消毒（包括一体化洗碗消毒机）不能正常运转，清洗消毒的餐饮具不符合要求。2、采用化学消毒的，产品有问题，或者消毒液配制、使用等出现问题，达不到消毒效果。',
    reasonAnalysis: '洗消人员未经过培训，不能正规使用物理和化学方法消毒餐饮具。',
    measures: '加强培训，责任到位，落实自查，抽检检查，对消毒效果进行比对。',
    isImportant: true,
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 41,
    checkProject: '保洁设施符合相关要求，保洁设施内存放的餐饮具保持清洁。',
    maybeRisk: '如果洗净消毒后的餐饮具，未按照密闭卫生的保洁柜存放，容易被污染。',
    reasonAnalysis: '存放餐饮具的保洁柜不足，餐饮具敞放，被污染。',
    measures: '加强培训，责任到位，落实自查，抽检检查，对保洁情况进行比对。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 42,
    checkProject:
      '使用集中清洗消毒餐饮具的，查验、留存集中消毒服务单位的营业执照复印件和消毒合格证明。餐饮具包装无破损、标识符合要求、在使用期限内。',
    maybeRisk:
      '使用不合格消毒餐饮具公司的产品，或者未查验、留存集中消毒服务单位的相关证件如果出现问题，更能沥青各自职责。餐饮具包装出现破损、标识不合格、超过使用期限等，容易使用到不合格产品。',
    reasonAnalysis: '未严格审查相关证照和合格证，未检查消毒餐具情况。',
    measures: '严格审查证照和相关手续，并检查产品是否符合相关要求。',
    isImportant: true,
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 43,
    checkProject: '未发现使用未经清洗消毒的餐饮具、重复使用一次性餐饮具。',
    maybeRisk: '1、存放时间较久，重新使用未清洗消毒。2、重复使用一次性餐饮具，不能保证餐具是合格产品。',
    reasonAnalysis: '人员消毒意识差，因节约而违规重复使用一次性餐具。',
    measures: '严把餐具消毒关，避免出现重复使用一次性餐具的情况。',
    isImportant: true,
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 44,
    checkProject: '主动对消费者进行防止食品浪费提示提醒。',
    maybeRisk: '违反《反食品浪费法》相关规定。',
    reasonAnalysis: '对《反食品浪费法》宣传不够，责任落实不到位。',
    measures: '对《反食品浪费法》多宣传。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 45,
    checkProject: '未发现诱导、误导消费者超量点餐造成明显浪费。',
    maybeRisk: '违反《反食品浪费法》相关规定，出现浪费食品的现象。',
    reasonAnalysis: '从利益出发想多卖食品，违规赚取利润。',
    measures: '对《反食品浪费法》多宣传，落实责任。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 46,
    checkProject: '未发现经营过程中存在严重浪费。',
    maybeRisk: '违反《反食品浪费法》相关规定，出现浪费食品的现象。',
    reasonAnalysis: '对《反食品浪费法》宣传不够，责任落实不到位。',
    measures: '对《反食品浪费法》多宣传。落实责任。',
    isImportant: true,
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 47,
    checkProject: '设立并公布食品安全投诉举报电话、电子邮箱、意见箱等，及时处理投诉举报或意见建议。',
    maybeRisk: '《反食品浪费法》宣传不到位，相关要求未落实。',
    reasonAnalysis: '对《反食品浪费法》重视度不够，责任落实不到位。',
    measures: '对《反食品浪费法》多宣传。硬件到位，落实责任。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 48,
    checkProject: '学校应建立由学校负责人、教职工代表、学生代表、家长代表等参与的食品安全民主监督机制。',
    maybeRisk: '学校未建立民主监督机制，当出现食品安全事件时，不易化解食品安全矛盾。',
    reasonAnalysis: '对学校建立民主监督机制认识不足。',
    measures: '立即建立由学校负责人、教职工代表、学生代表、家长代表等参与的食品安全民主监督机制。',
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
  {
    index: 49,
    checkProject: '建立并执行安全生产管理制度，水、电、燃气及危化品等使用符合安全生产规范。',
    maybeRisk: '其他方面工作出现问题，同样有重大安全风险。',
    reasonAnalysis: '觉悟不高，对其他工作认识不足。',
    measures: '配合做好相关工作，避免出现其他生产安全事故',
    isImportant: true,
    responsibleDepartment: '',
    checkResult: '',
    checked: false,
    finishDate: '',
  },
];
