/**
 * 随机打散字符串
 * @param {number} n 长度
 * @param {string} str 字符串
 * @returns
 */
function generateMixed(n, str) {
  var res = '';
  for (var i = 0; i < n; i++) {
    var id = Math.ceil(Math.random() * 35);
    res += str[id];
  }
  return res;
}

/**
 * 生成随机数
 * @param {number} min 最小值
 * @param {number} max 最大值
 * @returns
 */
function getRandomNum(min, max) {
  var range = max - min;
  var rand = Math.random();
  return min + Math.round(rand * range);
}

/**
 * 生成随机IP
 * @returns
 */
function mockIp() {
  return `10.${getRandomNum(1, 254)}.${getRandomNum(1, 254)}.${getRandomNum(1, 254)}`;
}

function mockReqId() {
  return `${getRandomNum(100000, 999999)}.${new Date().valueOf()}${getRandomNum(1000, 9999)}.${getRandomNum(
    10000000,
    99999999,
  )}`;
}

const foodItems = [
  {
    item_id: '60',
    enterprise_id: '0',
    template_id: '7',
    program_seq: '一',
    program_name: '通用检查项',
    item_seq: 1,
    title: '大型企业应至少抽查2名从业人员是否掌握本岗位食品安全知识。',
    section_1: '合格',
    section_2: '不合格',
    section_3: '',
    section_4: '',
    solution: '',
    hidden_danger: '',
    anaylise: '',
    created_at: '2023-10-10T07:31:26.000Z',
    updated_at: '2023-10-10T07:31:26.000Z',
    deleted_at: null,
  },
  {
    item_id: '61',
    enterprise_id: '0',
    template_id: '7',
    program_seq: '一',
    program_name: '通用检查项',
    item_seq: 2,
    title: '食品经营场所环境整洁卫生，食品（含食品添加剂、食用农产品，下同）是否有被污染的风险。',
    section_1: '合格',
    section_2: '不合格',
    section_3: '',
    section_4: '',
    solution: '',
    hidden_danger: '',
    anaylise: '',
    created_at: '2023-10-10T07:31:26.000Z',
    updated_at: '2023-10-10T07:31:26.000Z',
    deleted_at: null,
  },
  {
    item_id: '62',
    enterprise_id: '0',
    template_id: '7',
    program_seq: '一',
    program_name: '通用检查项',
    item_seq: 3,
    title: '销售人员在销售场所是否有饮食、吸烟、随地吐痰、乱扔废弃物等行为。',
    section_1: '合格',
    section_2: '不合格',
    section_3: '',
    section_4: '',
    solution: '',
    hidden_danger: '',
    anaylise: '',
    created_at: '2023-10-10T07:31:26.000Z',
    updated_at: '2023-10-10T07:31:26.000Z',
    deleted_at: null,
  },
  {
    item_id: '63',
    enterprise_id: '0',
    template_id: '7',
    program_seq: '一',
    program_name: '通用检查项',
    item_seq: 4,
    title: '接触直接入口或不需清洗即可加工的散装食品时，是否戴口罩、手套和帽子，头发不外露。',
    section_1: '合格',
    section_2: '不合格',
    section_3: '',
    section_4: '',
    solution: '',
    hidden_danger: '',
    anaylise: '',
    created_at: '2023-10-10T07:31:26.000Z',
    updated_at: '2023-10-10T07:31:26.000Z',
    deleted_at: null,
  },
  {
    item_id: '64',
    enterprise_id: '0',
    template_id: '7',
    program_seq: '一',
    program_name: '通用检查项',
    item_seq: 5,
    title: '贮存食品的库房、设备、容器、工具是否清洁、安全、无害，设备运转是否正常，温度是否度符合食品安全要求。',
    section_1: '合格',
    section_2: '不合格',
    section_3: '',
    section_4: '',
    solution: '',
    hidden_danger: '',
    anaylise: '',
    created_at: '2023-10-10T07:31:26.000Z',
    updated_at: '2023-10-10T07:31:26.000Z',
    deleted_at: null,
  },
  {
    item_id: '65',
    enterprise_id: '0',
    template_id: '7',
    program_seq: '一',
    program_name: '通用检查项',
    item_seq: 6,
    title: '是否按是否按照食品标签标示要求贮存、销售食品。',
    section_1: '合格',
    section_2: '不合格',
    section_3: '',
    section_4: '',
    solution: '',
    hidden_danger: '',
    anaylise: '',
    created_at: '2023-10-10T07:31:26.000Z',
    updated_at: '2023-10-10T07:31:26.000Z',
    deleted_at: null,
  },
  {
    item_id: '66',
    enterprise_id: '0',
    template_id: '7',
    program_seq: '一',
    program_name: '通用检查项',
    item_seq: 7,
    title: '经营场所食品广告或宣传的内容真实合法，是否有虚假内容，是否涉及疾病预防、治疗功能。',
    section_1: '合格',
    section_2: '不合格',
    section_3: '',
    section_4: '',
    solution: '',
    hidden_danger: '',
    anaylise: '',
    created_at: '2023-10-10T07:31:26.000Z',
    updated_at: '2023-10-10T07:31:26.000Z',
    deleted_at: null,
  },
  {
    item_id: '67',
    enterprise_id: '0',
    template_id: '7',
    program_seq: '一',
    program_name: '通用检查项',
    item_seq: 8,
    title:
      '至少抽查2批次食品供货票据，记录所采购食品供货单位地址、联系方式以及食品名称、规格、数量、生产日期或批号、保质期、进货日期等是否规范完整。',
    section_1: '合格',
    section_2: '不合格',
    section_3: '',
    section_4: '',
    solution: '',
    hidden_danger: '',
    anaylise: '',
    created_at: '2023-10-10T07:31:26.000Z',
    updated_at: '2023-10-10T07:31:26.000Z',
    deleted_at: null,
  },
  {
    item_id: '68',
    enterprise_id: '0',
    template_id: '7',
    program_seq: '一',
    program_name: '通用检查项',
    item_seq: 9,
    title: '至少抽查2批次食用农产品是否具有达标承诺合格证明或其他合格证明文件。',
    section_1: '合格',
    section_2: '不合格',
    section_3: '',
    section_4: '',
    solution: '',
    hidden_danger: '',
    anaylise: '',
    created_at: '2023-10-10T07:31:26.000Z',
    updated_at: '2023-10-10T07:31:26.000Z',
    deleted_at: null,
  },
  {
    item_id: '69',
    enterprise_id: '0',
    template_id: '7',
    program_seq: '一',
    program_name: '通用检查项',
    item_seq: 10,
    title: '至少抽查2批次进口预包装食品是否有中文标签，是否有国家出入境检验检疫部门出具的入境货物检验检疫证明。',
    section_1: '合格',
    section_2: '不合格',
    section_3: '',
    section_4: '',
    solution: '',
    hidden_danger: '',
    anaylise: '',
    created_at: '2023-10-10T07:31:26.000Z',
    updated_at: '2023-10-10T07:31:26.000Z',
    deleted_at: null,
  },
  {
    item_id: '70',
    enterprise_id: '0',
    template_id: '7',
    program_seq: '一',
    program_name: '通用检查项',
    item_seq: 11,
    title: '至少抽查2批次进口冷链食品是否具备“三证明一信息”（检疫证明、消毒证明、出仓证明、“川食安”平台追溯信息）。',
    section_1: '合格',
    section_2: '不合格',
    section_3: '',
    section_4: '',
    solution: '',
    hidden_danger: '',
    anaylise: '',
    created_at: '2023-10-10T07:31:26.000Z',
    updated_at: '2023-10-10T07:31:26.000Z',
    deleted_at: null,
  },
  {
    item_id: '71',
    enterprise_id: '0',
    template_id: '7',
    program_seq: '一',
    program_name: '通用检查项',
    item_seq: 12,
    title: '至少抽查2批次肉类具有检验检疫合格证明和肉品品质检验合格证明。',
    section_1: '合格',
    section_2: '不合格',
    section_3: '',
    section_4: '',
    solution: '',
    hidden_danger: '',
    anaylise: '',
    created_at: '2023-10-10T07:31:26.000Z',
    updated_at: '2023-10-10T07:31:26.000Z',
    deleted_at: null,
  },
  {
    item_id: '72',
    enterprise_id: '0',
    template_id: '7',
    program_seq: '一',
    program_name: '通用检查项',
    item_seq: 13,
    title:
      '至少抽查2批次食品标签、说明书是否清楚，是否准确标注食品的名称、生产日期或批号、保质期、生产者名称及联系方式等内容。',
    section_1: '合格',
    section_2: '不合格',
    section_3: '',
    section_4: '',
    solution: '',
    hidden_danger: '',
    anaylise: '',
    created_at: '2023-10-10T07:31:26.000Z',
    updated_at: '2023-10-10T07:31:26.000Z',
    deleted_at: null,
  },
  {
    item_id: '73',
    enterprise_id: '0',
    template_id: '7',
    program_seq: '一',
    program_name: '通用检查项',
    item_seq: 14,
    title: '是否对临近保质期的食品分类管理，并作特别标示或者集中陈列出售。',
    section_1: '合格',
    section_2: '不合格',
    section_3: '',
    section_4: '',
    solution: '',
    hidden_danger: '',
    anaylise: '',
    created_at: '2023-10-10T07:31:26.000Z',
    updated_at: '2023-10-10T07:31:26.000Z',
    deleted_at: null,
  },
  {
    item_id: '74',
    enterprise_id: '0',
    template_id: '7',
    program_seq: '一',
    program_name: '通用检查项',
    item_seq: 15,
    title: '是否及时清理经营场所内腐烂变质、感官异常、混有异物或者超过保质期等禁止销售的食品。',
    section_1: '合格',
    section_2: '不合格',
    section_3: '',
    section_4: '',
    solution: '',
    hidden_danger: '',
    anaylise: '',
    created_at: '2023-10-10T07:31:26.000Z',
    updated_at: '2023-10-10T07:31:26.000Z',
    deleted_at: null,
  },
  {
    item_id: '193',
    enterprise_id: '3',
    template_id: '7',
    program_seq: '0',
    program_name: '',
    item_seq: 0,
    title: '继续新增哦',
    section_1: '',
    section_2: '',
    section_3: '',
    section_4: '',
    solution: '',
    hidden_danger: '',
    anaylise: '',
    created_at: '2024-06-17T02:39:02.000Z',
    updated_at: '2024-06-17T02:39:02.000Z',
    deleted_at: null,
  },
];

module.exports = {
  generateMixed,
  mockIp,
  mockReqId,
  getRandomNum,
  foodItems,
};
